# Generated by Django 2.0.2 on 2018-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_api', '0003_auto_20180304_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
